services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: kasir
      POSTGRES_PASSWORD: kasir
      POSTGRES_DB: kasir
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kasir -d kasir"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      NODE_ENV: production
      PORT: 8080
      DATABASE_URL: postgres://kasir:kasir@db:5432/kasir
      SESSION_SECRET: ganti-di-production
      COOKIE_SECURE: "false"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  pgdata:
